<?php
final class Data43FormRegistry
{
    public static function schemas(): array
    {
        return [
            'PERSON' => [
                'label'=>'บุคคล',
                'icon'=>'bi-person-vcard',
                'pk'=>['HOSPCODE','PID'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                    ['name'=>'PID','label'=>'PID','type'=>'auto','required'=>true],
                    ['name'=>'CID','label'=>'เลขบัตรประชาชน','type'=>'text','maxlength'=>13],
                    ['name'=>'HID','label'=>'HID / บ้าน','type'=>'home-search'],
                    ['name'=>'PRENAME','label'=>'คำนำหน้า','type'=>'text'],
                    ['name'=>'NAME','label'=>'ชื่อ','type'=>'text','required'=>true],
                    ['name'=>'LNAME','label'=>'นามสกุล','type'=>'text','required'=>true],
                    ['name'=>'SEX','label'=>'เพศ','type'=>'select','options'=>['1'=>'ชาย','2'=>'หญิง']],
                    ['name'=>'BIRTH','label'=>'วันเกิด','type'=>'thai-date','required'=>true],
                    ['name'=>'TYPEAREA','label'=>'สถานะบุคคลในพื้นที่','type'=>'select','required'=>true,'options'=>[
                        '1'=>'มีชื่อในทะเบียนบ้านและอยู่จริง',
                        '2'=>'มีชื่อในทะเบียนบ้านแต่ไม่อยู่จริง',
                        '3'=>'อาศัยอยู่จริงแต่ทะเบียนบ้านอยู่นอกพื้นที่',
                        '4'=>'อยู่นอกพื้นที่/มารับบริการ',
                        '5'=>'อาศัยในพื้นที่แต่ไม่มีทะเบียนบ้านในพื้นที่',
                    ]],
                    ['name'=>'DISCHARGE','label'=>'สถานะจำหน่าย','type'=>'select','options'=>[
                        '1'=>'ตาย','2'=>'ย้าย','3'=>'สาบสูญ','9'=>'ไม่จำหน่าย'
                    ]],
                    ['name'=>'DDISCHARGE','label'=>'วันที่จำหน่าย','type'=>'thai-date'],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                ],
            ],
            'HOME' => [
                'label'=>'บ้าน',
                'icon'=>'bi-house-heart',
                'pk'=>['HOSPCODE','HID'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'HID','label'=>'HID','type'=>'auto','required'=>true],
                    ['name'=>'HOUSE','label'=>'บ้านเลขที่','type'=>'text'],
                    ['name'=>'VILLAGE','label'=>'หมู่บ้าน','type'=>'text','placeholder'=>'01 หรือ A0'],
                    ['name'=>'TAMBON','label'=>'ตำบล (รหัส 2 หลัก)','type'=>'text','maxlength'=>2],
                    ['name'=>'AMPUR','label'=>'อำเภอ (รหัส 2 หลัก)','type'=>'text','maxlength'=>2],
                    ['name'=>'CHANGWAT','label'=>'จังหวัด (รหัส 2 หลัก)','type'=>'text','maxlength'=>2],
                    ['name'=>'LATITUDE','label'=>'Latitude','type'=>'decimal','readonly'=>true],
                    ['name'=>'LONGITUDE','label'=>'Longitude','type'=>'decimal','readonly'=>true],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                ],
            ],
            'ADDRESS' => [
                'label'=>'ที่อยู่',
                'icon'=>'bi-geo-alt',
                'pk'=>['HOSPCODE','PID','ADDRESSTYPE'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'ADDRESSTYPE','label'=>'ประเภทที่อยู่','type'=>'select','required'=>true,'options'=>['1'=>'ทะเบียนบ้าน','2'=>'ที่อยู่ปัจจุบัน']],
                    ['name'=>'HOUSE_ID','label'=>'รหัสบ้านตามทะเบียน','type'=>'text'],
                    ['name'=>'HOUSE','label'=>'บ้านเลขที่','type'=>'text'],
                    ['name'=>'VILLAGE','label'=>'หมู่บ้าน','type'=>'text'],
                    ['name'=>'TAMBON','label'=>'ตำบล','type'=>'text','maxlength'=>2],
                    ['name'=>'AMPUR','label'=>'อำเภอ','type'=>'text','maxlength'=>2],
                    ['name'=>'CHANGWAT','label'=>'จังหวัด','type'=>'text','maxlength'=>2],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                ],
            ],
            'CHRONIC' => [
                'label'=>'โรคเรื้อรัง',
                'icon'=>'bi-heart-pulse',
                'pk'=>['HOSPCODE','PID','DATE_DIAG','CHRONIC'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'DATE_DIAG','label'=>'วันที่วินิจฉัย','type'=>'thai-date','required'=>true],
                    ['name'=>'CHRONIC','label'=>'รหัส ICD-10-TM','type'=>'text','required'=>true,'placeholder'=>'เช่น E11.9'],
                    ['name'=>'HOSP_DX','label'=>'หน่วยบริการที่วินิจฉัย','type'=>'text'],
                    ['name'=>'TYPEDISCH','label'=>'สถานะโรค','type'=>'select','options'=>[
                        '01'=>'หาย','02'=>'ตาย','03'=>'ยังรักษาอยู่','04'=>'ไม่ทราบ','05'=>'รอจำหน่าย/เฝ้าระวัง',
                        '06'=>'ขาดการรักษา','07'=>'ครบการรักษา','08'=>'ภาวะสงบ','09'=>'ปฏิเสธการรักษา','10'=>'ออกจากพื้นที่','11'=>'กลับเป็นซ้ำ'
                    ]],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                ],
            ],
            'VILLAGE' => [
                'label'=>'หมู่บ้าน/ชุมชน',
                'icon'=>'bi-buildings',
                'pk'=>['HOSPCODE','VID'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'VID','label'=>'รหัสชุมชน CCAATTMM','type'=>'text','maxlength'=>8,'required'=>true,'placeholder'=>'เช่น 33010101 หรือ 330101A0'],
                    ['name'=>'NTRADITIONAL','label'=>'จำนวนแพทย์แผนไทย/พื้นบ้าน','type'=>'decimal'],
                    ['name'=>'NMONK','label'=>'จำนวนพระในชุมชน','type'=>'decimal'],
                    ['name'=>'NRELIGIONLEADER','label'=>'จำนวนผู้นำศาสนา','type'=>'decimal'],
                    ['name'=>'NBROADCAST','label'=>'จำนวนหอกระจายข่าว','type'=>'decimal'],
                    ['name'=>'NRADIO','label'=>'จำนวนสถานีวิทยุชุมชน','type'=>'decimal'],
                    ['name'=>'NPCHC','label'=>'จำนวนศูนย์สาธารณสุขมูลฐาน','type'=>'decimal'],
                    ['name'=>'NCLINIC','label'=>'จำนวนคลินิก','type'=>'decimal'],
                    ['name'=>'NDRUGSTORE','label'=>'จำนวนร้านขายยา','type'=>'decimal'],
                    ['name'=>'NCHILDCENTER','label'=>'จำนวนศูนย์พัฒนาเด็กเล็ก','type'=>'decimal'],
                    ['name'=>'NPSCHOOL','label'=>'จำนวนโรงเรียนประถม','type'=>'decimal'],
                    ['name'=>'NSSCHOOL','label'=>'จำนวนโรงเรียนมัธยม','type'=>'decimal'],
                    ['name'=>'NTEMPLE','label'=>'จำนวนวัด','type'=>'decimal'],
                    ['name'=>'NRELIGIOUSPLACE','label'=>'จำนวนศาสนสถานอื่น','type'=>'decimal'],
                    ['name'=>'NMARKET','label'=>'จำนวนตลาดสด','type'=>'decimal'],
                    ['name'=>'NSHOP','label'=>'จำนวนร้านขายของชำ','type'=>'decimal'],
                    ['name'=>'NFOODSHOP','label'=>'จำนวนร้านอาหาร','type'=>'decimal'],
                    ['name'=>'NSTALL','label'=>'จำนวนหาบเร่/แผงลอย','type'=>'decimal'],
                    ['name'=>'NRAINTANK','label'=>'จำนวนถังเก็บน้ำฝน','type'=>'decimal'],
                    ['name'=>'NCHICKENFARM','label'=>'จำนวนฟาร์มสัตว์ปีก','type'=>'decimal'],
                    ['name'=>'NPIGFARM','label'=>'จำนวนฟาร์มสุกร','type'=>'decimal'],
                    ['name'=>'WASTEWATER','label'=>'ระบบกำจัดน้ำเสีย','type'=>'select','options'=>['0'=>'ไม่มี','1'=>'มี','9'=>'ไม่ทราบ']],
                    ['name'=>'GARBAGE','label'=>'สถานที่จัดการมูลฝอย','type'=>'select','options'=>['0'=>'ไม่ทราบ','1'=>'ไม่มี','2'=>'ฝังกลบ','3'=>'เผา','4'=>'รวบรวม/คัดแยก/ใช้ประโยชน์','5'=>'รวบรวมไปกำจัดที่อื่น','6'=>'หมักทำปุ๋ย','9'=>'อื่นๆ']],
                    ['name'=>'NFACTORY','label'=>'จำนวนโรงงานอุตสาหกรรม','type'=>'decimal'],
                    ['name'=>'LATITUDE','label'=>'Latitude ใจกลางหมู่บ้าน','type'=>'decimal','readonly'=>true],
                    ['name'=>'LONGITUDE','label'=>'Longitude ใจกลางหมู่บ้าน','type'=>'decimal','readonly'=>true],
                    ['name'=>'OUTDATE','label'=>'วันที่แยกชุมชนออกนอกเขต','type'=>'thai-date'],
                    ['name'=>'NUMACTUALLY','label'=>'จำนวนแหล่งอบายมุข','type'=>'decimal'],
                    ['name'=>'RISKTYPE','label'=>'ประเภทความเสี่ยงภัยพิบัติ','type'=>'text','maxlength'=>3],
                    ['name'=>'NUMSTATELESS','label'=>'จำนวนชุมชนต่างด้าว','type'=>'decimal'],
                    ['name'=>'NEXERCISECLUB','label'=>'จำนวนชมรมออกกำลังกาย','type'=>'decimal'],
                    ['name'=>'NOLDERLYCLUB','label'=>'จำนวนชมรมผู้สูงอายุ','type'=>'decimal'],
                    ['name'=>'NDISABLECLUB','label'=>'จำนวนชมรมผู้พิการ','type'=>'decimal'],
                    ['name'=>'NNUMBERONECLUB','label'=>'จำนวนชมรม To Be Number 1','type'=>'decimal'],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                ],
            ],
            'DISABILITY' => [
                'label'=>'ผู้พิการ',
                'icon'=>'bi-universal-access',
                'pk'=>['HOSPCODE','PID','DISABTYPE'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'DISABID','label'=>'เลขทะเบียนผู้พิการ','type'=>'text','maxlength'=>13],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'DISABTYPE','label'=>'ประเภทความพิการ','type'=>'select','required'=>true,'options'=>[
                        '1'=>'การเห็น','2'=>'การได้ยิน/สื่อความหมาย','3'=>'การเคลื่อนไหว/ร่างกาย',
                        '4'=>'จิตใจ/พฤติกรรม','5'=>'สติปัญญา','6'=>'การเรียนรู้','7'=>'ออทิสติก'
                    ]],
                    ['name'=>'DISABCAUSE','label'=>'สาเหตุความพิการ','type'=>'select','options'=>['1'=>'แต่กำเนิด','2'=>'บาดเจ็บ','3'=>'โรค']],
                    ['name'=>'DIAGCODE','label'=>'ICD-10-TM สาเหตุความพิการ','type'=>'text','maxlength'=>6],
                    ['name'=>'DATE_DETECT','label'=>'วันที่ตรวจพบความพิการ','type'=>'thai-date','required'=>true],
                    ['name'=>'DATE_DISAB','label'=>'วันที่เริ่มมีความพิการ','type'=>'thai-date'],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                ],
            ],
            'SERVICE' => [
                'label'=>'การรับบริการ',
                'icon'=>'bi-clipboard2-pulse',
                'pk'=>['HOSPCODE','PID','SEQ'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'HN','label'=>'HN','type'=>'text','maxlength'=>15],
                    ['name'=>'SEQ','label'=>'SEQ (1 visit)','type'=>'text','maxlength'=>16,'required'=>true],
                    ['name'=>'DATE_SERV','label'=>'วันที่ให้บริการ','type'=>'thai-date','required'=>true],
                    ['name'=>'TIME_SERV','label'=>'เวลาให้บริการ HHMMSS','type'=>'text','maxlength'=>6],
                    ['name'=>'LOCATION','label'=>'ที่อยู่ผู้รับบริการ','type'=>'select','options'=>['1'=>'ในเขตรับผิดชอบ','2'=>'นอกเขตรับผิดชอบ']],
                    ['name'=>'INTIME','label'=>'ช่วงเวลา','type'=>'select','options'=>['1'=>'ในเวลาราชการ','2'=>'นอกเวลาราชการ']],
                    ['name'=>'INSTYPE','label'=>'ประเภทสิทธิการรักษา','type'=>'text','maxlength'=>4,'required'=>true],
                    ['name'=>'INSID','label'=>'เลขที่บัตรสิทธิ','type'=>'text','maxlength'=>18],
                    ['name'=>'MAIN','label'=>'หน่วยบริการหลัก','type'=>'text','maxlength'=>5],
                    ['name'=>'TYPEIN','label'=>'ประเภทการมารับบริการ','type'=>'select','required'=>true,'options'=>['1'=>'มาเอง','2'=>'ตามนัด','3'=>'ส่งต่อจากหน่วยบริการอื่น','4'=>'EMS']],
                    ['name'=>'REFERINHOSP','label'=>'หน่วยบริการที่ส่งมา','type'=>'text','maxlength'=>5],
                    ['name'=>'CAUSEIN','label'=>'สาเหตุการส่งมา','type'=>'select','options'=>['1'=>'วินิจฉัยและรักษา','2'=>'วินิจฉัย','3'=>'รักษา/ฟื้นฟูต่อเนื่อง','4'=>'ดูแลต่อใกล้บ้าน','5'=>'ความต้องการผู้ป่วย']],
                    ['name'=>'CHIEFCOMP','label'=>'อาการสำคัญ','type'=>'text','maxlength'=>255],
                    ['name'=>'SERVPLACE','label'=>'สถานที่รับบริการ','type'=>'select','required'=>true,'options'=>['1'=>'ในหน่วยบริการ','2'=>'นอกหน่วยบริการ']],
                    ['name'=>'BTEMP','label'=>'อุณหภูมิ','type'=>'decimal'],
                    ['name'=>'SBP','label'=>'SBP','type'=>'decimal'],
                    ['name'=>'DBP','label'=>'DBP','type'=>'decimal'],
                    ['name'=>'PR','label'=>'ชีพจร','type'=>'decimal'],
                    ['name'=>'RR','label'=>'อัตราหายใจ','type'=>'decimal'],
                    ['name'=>'TYPEOUT','label'=>'สถานะเมื่อเสร็จบริการ','type'=>'select','required'=>true,'options'=>[
                        '1'=>'กลับบ้าน','2'=>'รับไว้รักษา IPD','3'=>'ส่งต่อ','4'=>'เสียชีวิต','5'=>'เสียชีวิตก่อนถึง',
                        '6'=>'เสียชีวิตระหว่างส่งต่อ','7'=>'ปฏิเสธรักษา','8'=>'หนีกลับ','9'=>'บริการไม่มีคำวินิจฉัย'
                    ]],
                    ['name'=>'REFEROUTHOSP','label'=>'หน่วยบริการที่ส่งต่อ','type'=>'text','maxlength'=>5],
                    ['name'=>'CAUSEOUT','label'=>'สาเหตุส่งต่อ','type'=>'select','options'=>['1'=>'วินิจฉัยและรักษา','2'=>'วินิจฉัย','3'=>'รักษา/ฟื้นฟูต่อเนื่อง','4'=>'ดูแลต่อใกล้บ้าน','5'=>'ความต้องการผู้ป่วย']],
                    ['name'=>'COST','label'=>'ราคาทุน','type'=>'decimal'],
                    ['name'=>'PRICE','label'=>'ค่าบริการทั้งหมด','type'=>'decimal','required'=>true],
                    ['name'=>'PAYPRICE','label'=>'ค่าบริการที่ต้องจ่ายเอง','type'=>'decimal','required'=>true],
                    ['name'=>'ACTUALPAY','label'=>'เงินที่จ่ายจริง','type'=>'decimal','required'=>true],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                ],
            ],
            'NCDSCREEN' => [
                'label'=>'คัดกรอง NCD',
                'icon'=>'bi-activity',
                'pk'=>['HOSPCODE','PID','DATE_SERV'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'SEQ','label'=>'SEQ','type'=>'text','maxlength'=>16],
                    ['name'=>'DATE_SERV','label'=>'วันที่ตรวจ','type'=>'thai-date','required'=>true],
                    ['name'=>'SERVPLACE','label'=>'บริการใน/นอกหน่วย','type'=>'select','required'=>true,'options'=>['1'=>'ในหน่วยบริการ','2'=>'นอกหน่วยบริการ']],
                    ['name'=>'SMOKE','label'=>'ประวัติสูบบุหรี่','type'=>'select','options'=>['1'=>'ไม่สูบ','2'=>'นานๆครั้ง','3'=>'เป็นครั้งคราว','4'=>'ประจำ','9'=>'ไม่ทราบ']],
                    ['name'=>'ALCOHOL','label'=>'ประวัติดื่มแอลกอฮอล์','type'=>'select','options'=>['1'=>'ไม่ดื่ม','2'=>'นานๆครั้ง','3'=>'เป็นครั้งคราว','4'=>'ประจำ','9'=>'ไม่ทราบ']],
                    ['name'=>'DMFAMILY','label'=>'ประวัติ DM ญาติสายตรง','type'=>'select','options'=>['1'=>'มี','2'=>'ไม่มี','9'=>'ไม่ทราบ']],
                    ['name'=>'HTFAMILY','label'=>'ประวัติ HT ญาติสายตรง','type'=>'select','options'=>['1'=>'มี','2'=>'ไม่มี','9'=>'ไม่ทราบ']],
                    ['name'=>'WEIGHT','label'=>'น้ำหนัก (กก.)','type'=>'decimal','required'=>true],
                    ['name'=>'HEIGHT','label'=>'ส่วนสูง (ซม.)','type'=>'decimal','required'=>true],
                    ['name'=>'WAIST_CM','label'=>'รอบเอว (ซม.)','type'=>'decimal','required'=>true],
                    ['name'=>'SBP_1','label'=>'SBP ครั้งที่ 1','type'=>'decimal','required'=>true],
                    ['name'=>'DBP_1','label'=>'DBP ครั้งที่ 1','type'=>'decimal','required'=>true],
                    ['name'=>'SBP_2','label'=>'SBP ครั้งที่ 2','type'=>'decimal'],
                    ['name'=>'DBP_2','label'=>'DBP ครั้งที่ 2','type'=>'decimal'],
                    ['name'=>'BSLEVEL','label'=>'ระดับน้ำตาลในเลือด','type'=>'decimal'],
                    ['name'=>'BSTEST','label'=>'วิธีตรวจน้ำตาล','type'=>'select','options'=>['1'=>'Venous fasting','2'=>'Venous non-fasting','3'=>'Capillary fasting','4'=>'Capillary non-fasting','9'=>'ไม่ตรวจ']],
                    ['name'=>'SCREENPLACE','label'=>'สถานที่คัดกรอง','type'=>'text','maxlength'=>5],
                    ['name'=>'PROVIDER','label'=>'ผู้ให้บริการ','type'=>'text','maxlength'=>15],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                    ['name'=>'SCREENPLACE9','label'=>'สถานที่คัดกรอง 9 หลัก','type'=>'text','maxlength'=>9],
                ],
            ],
            'PRENATAL' => [
                'label'=>'ประวัติการตั้งครรภ์',
                'icon'=>'bi-person-hearts',
                'pk'=>['HOSPCODE','PID','GRAVIDA'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'GRAVIDA','label'=>'ครรภ์ที่','type'=>'text','maxlength'=>2,'required'=>true],
                    ['name'=>'LMP','label'=>'วันแรกของประจำเดือนครั้งสุดท้าย','type'=>'thai-date','required'=>true],
                    ['name'=>'EDC','label'=>'กำหนดคลอด','type'=>'thai-date'],
                    ['name'=>'VDRL_RESULT','label'=>'VDRL','type'=>'select','required'=>true,'options'=>['1'=>'ปกติ','2'=>'ผิดปกติ','3'=>'ไม่ตรวจ','4'=>'รอผล','9'=>'ไม่ทราบ']],
                    ['name'=>'HB_RESULT','label'=>'HB','type'=>'select','required'=>true,'options'=>['1'=>'ปกติ','2'=>'ผิดปกติ','3'=>'ไม่ตรวจ','4'=>'รอผล','9'=>'ไม่ทราบ']],
                    ['name'=>'HIV_RESULT','label'=>'HIV','type'=>'select','required'=>true,'options'=>['1'=>'ปกติ','2'=>'ผิดปกติ','3'=>'ไม่ตรวจ','4'=>'รอผล','9'=>'ไม่ทราบ']],
                    ['name'=>'DATE_HCT','label'=>'วันที่ตรวจ HCT','type'=>'thai-date'],
                    ['name'=>'HCT_RESULT','label'=>'HCT (%)','type'=>'decimal'],
                    ['name'=>'THALASSEMIA','label'=>'Thalassemia','type'=>'select','required'=>true,'options'=>['1'=>'ปกติ','2'=>'ผิดปกติ','3'=>'ไม่ตรวจ','4'=>'รอผล','9'=>'ไม่ทราบ']],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'PROVIDER','label'=>'ผู้ให้บริการ','type'=>'text','maxlength'=>15],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'HEIGHT','label'=>'ส่วนสูง (ซม.)','type'=>'decimal','required'=>true],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                ],
            ],
            'ANC' => [
                'label'=>'ฝากครรภ์ ANC',
                'icon'=>'bi-heart-pulse-fill',
                'pk'=>['HOSPCODE','PID','DATE_SERV'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'SEQ','label'=>'SEQ','type'=>'text','maxlength'=>16],
                    ['name'=>'DATE_SERV','label'=>'วันที่ให้บริการ','type'=>'thai-date','required'=>true],
                    ['name'=>'GRAVIDA','label'=>'ครรภ์ที่','type'=>'text','maxlength'=>2,'required'=>true],
                    ['name'=>'ANCNO','label'=>'ANC ช่วงที่','type'=>'text','maxlength'=>1],
                    ['name'=>'GA','label'=>'อายุครรภ์ (สัปดาห์)','type'=>'text','maxlength'=>2,'required'=>true],
                    ['name'=>'ANCRESULT','label'=>'ผลตรวจ','type'=>'select','required'=>true,'options'=>['1'=>'ปกติ','2'=>'ผิดปกติ','9'=>'ไม่ทราบ']],
                    ['name'=>'ANCPLACE','label'=>'สถานที่รับบริการ','type'=>'text','maxlength'=>5],
                    ['name'=>'PROVIDER','label'=>'ผู้ให้บริการ','type'=>'text','maxlength'=>15],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'WEIGHT','label'=>'น้ำหนัก (กก.)','type'=>'decimal','required'=>true],
                    ['name'=>'HOSPCODE9','label'=>'รหัสหน่วยบริการ 9 หลัก','type'=>'auto'],
                    ['name'=>'ANCPLACE9','label'=>'สถานที่รับบริการ 9 หลัก','type'=>'text','maxlength'=>9],
                ],
            ],
            'DEATH' => [
                'label'=>'เสียชีวิต',
                'icon'=>'bi-file-medical',
                'pk'=>['HOSPCODE','PID'],
                'fields'=>[
                    ['name'=>'HOSPCODE','label'=>'รหัสหน่วยบริการ','type'=>'auto','required'=>true],
                    ['name'=>'PID','label'=>'บุคคล','type'=>'person-search','required'=>true],
                    ['name'=>'CID','label'=>'CID','type'=>'auto-person'],
                    ['name'=>'DDEATH','label'=>'วันที่เสียชีวิต','type'=>'thai-date','required'=>true],
                    ['name'=>'CDEATH','label'=>'สาเหตุการตายหลัก (ICD-10-TM)','type'=>'text','required'=>true],
                    ['name'=>'CAUSEDEATH_A','label'=>'สาเหตุ A','type'=>'text'],
                    ['name'=>'CAUSEDEATH_B','label'=>'สาเหตุ B','type'=>'text'],
                    ['name'=>'CAUSEDEATH_C','label'=>'สาเหตุ C','type'=>'text'],
                    ['name'=>'CAUSEDEATH_D','label'=>'สาเหตุ D','type'=>'text'],
                    ['name'=>'D_UPDATE','label'=>'วันเวลาปรับปรุง','type'=>'auto','required'=>true],
                ],
            ],
        ];
    }

    public static function get(string $code): ?array
    {
        $code = strtoupper(trim($code));
        $all = self::schemas();
        return isset($all[$code]) ? ['code'=>$code] + $all[$code] : null;
    }

    public static function codes(): array
    {
        return array_keys(self::schemas());
    }

    public static function exportHeaders(string $code): array
    {
        $schema = self::get($code);
        if (!$schema) return [];
        return array_values(array_map(static fn(array $f): string => $f['name'], $schema['fields']));
    }
}
?>